// <auto-generated />
using System;
using ISA95DataGenerator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISA95DataGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260519000000_AddIsMassDataToGenericDataStore")]
    partial class AddIsMassDataToGenericDataStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Designer snapshot — see MigrationDbContextModelSnapshot for full model
        }
    }
}
