// <auto-generated />
using System;
using ISA95DataGenerator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISA95DataGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    partial class MigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.EntityMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FieldMappingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MigrationSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimaryKeyRuleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MigrationSessionId");

                    b.ToTable("EntityMappings");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.GenericDataStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StoreName");

                    b.HasIndex("StoreName", "RecordId")
                        .IsUnique();

                    b.ToTable("GenericDataStores");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Crew", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrewName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Crews");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentEquipmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductionLineId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Name");

                    b.HasIndex("ParentEquipmentId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClass", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("EquipmentClasses");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClassProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EquipmentClassId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaxValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MinValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueDataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentClassId");

                    b.ToTable("EquipmentClassProperties");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClassPropertyAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentClassPropertyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquipmentPropertyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentClassPropertyId");

                    b.HasIndex("EquipmentPropertyId");

                    b.ToTable("EquipmentClassPropertyAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaxValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MinValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueDataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EquipmentProperties");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentPropertyAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquipmentPropertyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessSegmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SamplingIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<string>("SamplingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EquipmentPropertyId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("EquipmentPropertyAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentUsage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CapacityPerRun")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessSegmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("EquipmentUsages");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.HierarchyScope", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquipmentLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("EquipmentLevel");

                    b.ToTable("HierarchyScopes");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.HierarchyScopeFlat", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Enterprise")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessCell")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductionLine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductionUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WorkCell")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkCenter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Enterprise");

                    b.HasIndex("Site");

                    b.ToTable("HierarchyScopesFlat");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.HierarchyScopeParentChild", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ChildEquipmentID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChildEquipmentLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentEquipmentID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentEquipmentLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildEquipmentID");

                    b.HasIndex("ParentEquipmentID");

                    b.ToTable("HierarchyScopeParentChilds");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.LineEquipment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductionLineId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("LineEquipments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultUoM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Name");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClass", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("MaterialClasses");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClassProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaxValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MinValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueDataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MaterialClassProperties");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClassPropertyAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialClassPropertyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialDefinitionPropertyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialClassPropertyId");

                    b.HasIndex("MaterialDefinitionPropertyId");

                    b.ToTable("MaterialClassPropertyAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialDefinitionProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValueUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MaterialDefinitionProperties");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialDefinitionPropertyAssignment", b =>
                {
                    b.Property<string>("Pk")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialDefinitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialDefinitionPropertyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValueUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Pk");

                    b.HasIndex("MaterialDefinitionId");

                    b.HasIndex("MaterialDefinitionPropertyId");

                    b.ToTable("MaterialDefinitionPropertyAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialLot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LotQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LotUoM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentLotId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProducedByProcessSegmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProducedDateTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceivedDateTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierOrProducerId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupplierOrProducerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialLots");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialSublot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Disposition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialLotId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("QuantityUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialLotId");

                    b.ToTable("MaterialSublots");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefSegmentAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimarySegment")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OperationEventDefinitionId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationsEventDefinitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessSegmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StartOrEndEvent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationEventDefinitionId");

                    b.HasIndex("OperationsEventDefinitionId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("OperationEventDefSegmentAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("CausesDowntime")
                        .HasColumnType("bit");

                    b.Property<bool>("CausesScrap")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EventCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RootCauseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventCategory");

                    b.HasIndex("EventCode");

                    b.ToTable("OperationEventDefinitions");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinitionProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PossibleValues")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OperationEventDefinitionProperties");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinitionPropertyAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationEventDefinitionId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationEventDefinitionPropertyId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationsEventDefinitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationsEventDefinitionPropertyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValueUnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationEventDefinitionId");

                    b.HasIndex("OperationEventDefinitionPropertyId");

                    b.HasIndex("OperationsEventDefinitionId");

                    b.HasIndex("OperationsEventDefinitionPropertyId");

                    b.ToTable("OperationEventDefinitionPropertyAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationsEventClass", b =>
                {
                    b.Property<string>("OperationsEventClassID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("OperationsEventClassID");

                    b.ToTable("OperationsEventClasses");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationsEventEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OperationsEventEntryID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationsEventRecordID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationsEventRecordID");

                    b.ToTable("OperationsEventEntries");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationsEventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationsEventDefinitionID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperationsEventRecordID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationsEventDefinitionID");

                    b.ToTable("OperationsEventRecords");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Plant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.ProcessSegment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DurationHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductMaterialId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProductMaterialId");

                    b.ToTable("ProcessSegments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.ProductionLine", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PlantId");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.SegmentBOM", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessSegmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("QtyPerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("SegmentBOMs");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Shift", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("int");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftNumber");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.ShiftCrewAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrewId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EffectiveDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShiftId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrewId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftCrewAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MigrationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogMessages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProcessedRecords")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ResultFilesPaths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("MigrationSessions");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MigrationSourceData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MigrationSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MigrationSessionId", "StoreName")
                        .IsUnique();

                    b.ToTable("MigrationSourceDatas");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.EquipmentActual", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DurationMinutes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EquipmentClassId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EquipmentState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentUse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HierarchyScope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegmentResponseId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("JobOrderId");

                    b.ToTable("EquipmentActuals");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.JobOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Command")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DispatchStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HierarchyScope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PlannedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessSegmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuantityUOM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkMasterId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkMasterVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchStatus");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("HierarchyScope");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("JobOrders");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.JobResponse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ActualQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrewId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HierarchyScope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialLotId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuantityUOM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShiftId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("JobOrderId");

                    b.HasIndex("JobState");

                    b.HasIndex("MaterialId");

                    b.ToTable("JobResponses");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.MaterialActual", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HierarchyScope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialClassId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialLotId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialSublotId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialUse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProcessSegmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("QuantityUOM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SegmentResponseId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StorageLocationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobOrderId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialLotId");

                    b.HasIndex("MaterialUse");

                    b.ToTable("MaterialActuals");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.SegmentResponse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DurationMinutes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HierarchyScope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobResponseId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessSegmentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SegmentState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobResponseId");

                    b.HasIndex("ProcessSegmentId");

                    b.ToTable("SegmentResponses");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.WorkRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HierarchyScope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkScheduleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyScope");

                    b.HasIndex("RequestState");

                    b.HasIndex("StartTime");

                    b.ToTable("WorkRequests");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.SourceDataTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MigrationSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MigrationSessionId");

                    b.ToTable("SourceDataTables");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.EntityMapping", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MigrationSession", "MigrationSession")
                        .WithMany("EntityMappings")
                        .HasForeignKey("MigrationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationSession");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Equipment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClass", "EquipmentClass")
                        .WithMany("Equipment")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.Equipment", "ParentEquipment")
                        .WithMany("ChildEquipment")
                        .HasForeignKey("ParentEquipmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EquipmentClass");

                    b.Navigation("ParentEquipment");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClass", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClass", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClassProperty", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClass", "EquipmentClass")
                        .WithMany("Properties")
                        .HasForeignKey("EquipmentClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EquipmentClass");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClassPropertyAssignment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClassProperty", "EquipmentClassProperty")
                        .WithMany("Assignments")
                        .HasForeignKey("EquipmentClassPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentProperty", "EquipmentProperty")
                        .WithMany()
                        .HasForeignKey("EquipmentPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentClassProperty");

                    b.Navigation("EquipmentProperty");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentPropertyAssignment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.Equipment", "Equipment")
                        .WithMany("PropertyAssignments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentProperty", "EquipmentProperty")
                        .WithMany("Assignments")
                        .HasForeignKey("EquipmentPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.ProcessSegment", "ProcessSegment")
                        .WithMany("PropertyAssignments")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("EquipmentProperty");

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentUsage", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.ProcessSegment", "ProcessSegment")
                        .WithMany("EquipmentUsages")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.LineEquipment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.ProductionLine", "ProductionLine")
                        .WithMany("LineEquipments")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Material", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClass", "MaterialClass")
                        .WithMany("Materials")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MaterialClass");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClassPropertyAssignment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClassProperty", "MaterialClassProperty")
                        .WithMany("Assignments")
                        .HasForeignKey("MaterialClassPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.MaterialDefinitionProperty", "MaterialDefinitionProperty")
                        .WithMany()
                        .HasForeignKey("MaterialDefinitionPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialClassProperty");

                    b.Navigation("MaterialDefinitionProperty");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialDefinitionPropertyAssignment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.MaterialDefinitionProperty", "MaterialDefinitionProperty")
                        .WithMany("Assignments")
                        .HasForeignKey("MaterialDefinitionPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialDefinitionProperty");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialLot", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.Material", "Material")
                        .WithMany("MaterialLots")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialSublot", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.MaterialLot", "MaterialLot")
                        .WithMany("MaterialSublots")
                        .HasForeignKey("MaterialLotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MaterialLot");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefSegmentAssignment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinition", "OperationEventDefinition")
                        .WithMany("SegmentAssignments")
                        .HasForeignKey("OperationEventDefinitionId");

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.ProcessSegment", "ProcessSegment")
                        .WithMany()
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationEventDefinition");

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinitionPropertyAssignment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinition", "OperationEventDefinition")
                        .WithMany("PropertyAssignments")
                        .HasForeignKey("OperationEventDefinitionId");

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinitionProperty", "OperationEventDefinitionProperty")
                        .WithMany("Assignments")
                        .HasForeignKey("OperationEventDefinitionPropertyId");

                    b.Navigation("OperationEventDefinition");

                    b.Navigation("OperationEventDefinitionProperty");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationsEventEntry", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.OperationsEventRecord", "OperationsEventRecord")
                        .WithMany("Entries")
                        .HasForeignKey("OperationsEventRecordID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OperationsEventRecord");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.ProductionLine", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.Plant", "Plant")
                        .WithMany("ProductionLines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.SegmentBOM", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.ProcessSegment", "ProcessSegment")
                        .WithMany("SegmentBOMs")
                        .HasForeignKey("ProcessSegmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProcessSegment");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.ShiftCrewAssignment", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.Crew", "Crew")
                        .WithMany("ShiftCrewAssignments")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ISA95DataGenerator.Domain.Entities.MasterData.Shift", "Shift")
                        .WithMany("ShiftCrewAssignments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MigrationSourceData", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MigrationSession", "MigrationSession")
                        .WithMany("SourceDatas")
                        .HasForeignKey("MigrationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationSession");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.EquipmentActual", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.ProcessData.JobOrder", "JobOrder")
                        .WithMany("EquipmentActuals")
                        .HasForeignKey("JobOrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("JobOrder");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.JobOrder", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.ProcessData.WorkRequest", "WorkRequest")
                        .WithMany("JobOrders")
                        .HasForeignKey("WorkRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("WorkRequest");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.JobResponse", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.ProcessData.JobOrder", "JobOrder")
                        .WithMany("JobResponses")
                        .HasForeignKey("JobOrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("JobOrder");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.MaterialActual", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.ProcessData.JobOrder", "JobOrder")
                        .WithMany("MaterialActuals")
                        .HasForeignKey("JobOrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("JobOrder");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.SegmentResponse", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.ProcessData.JobResponse", "JobResponse")
                        .WithMany("SegmentResponses")
                        .HasForeignKey("JobResponseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("JobResponse");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.SourceDataTable", b =>
                {
                    b.HasOne("ISA95DataGenerator.Domain.Entities.MigrationSession", "MigrationSession")
                        .WithMany("SourceTables")
                        .HasForeignKey("MigrationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationSession");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Crew", b =>
                {
                    b.Navigation("ShiftCrewAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Equipment", b =>
                {
                    b.Navigation("ChildEquipment");

                    b.Navigation("PropertyAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClass", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Equipment");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentClassProperty", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.EquipmentProperty", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Material", b =>
                {
                    b.Navigation("MaterialLots");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClass", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialClassProperty", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialDefinitionProperty", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.MaterialLot", b =>
                {
                    b.Navigation("MaterialSublots");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinition", b =>
                {
                    b.Navigation("PropertyAssignments");

                    b.Navigation("SegmentAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationEventDefinitionProperty", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.OperationsEventRecord", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Plant", b =>
                {
                    b.Navigation("ProductionLines");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.ProcessSegment", b =>
                {
                    b.Navigation("EquipmentUsages");

                    b.Navigation("PropertyAssignments");

                    b.Navigation("SegmentBOMs");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.ProductionLine", b =>
                {
                    b.Navigation("LineEquipments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MasterData.Shift", b =>
                {
                    b.Navigation("ShiftCrewAssignments");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.MigrationSession", b =>
                {
                    b.Navigation("EntityMappings");

                    b.Navigation("SourceDatas");

                    b.Navigation("SourceTables");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.JobOrder", b =>
                {
                    b.Navigation("EquipmentActuals");

                    b.Navigation("JobResponses");

                    b.Navigation("MaterialActuals");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.JobResponse", b =>
                {
                    b.Navigation("SegmentResponses");
                });

            modelBuilder.Entity("ISA95DataGenerator.Domain.Entities.ProcessData.WorkRequest", b =>
                {
                    b.Navigation("JobOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
